Add archbuild man page
archlinux/devtools pull request #65
Opened 2021-08-01 10:13 UTC by tsuibin

2021-08-01 13:59 UTC, jelly commented
Please also include a link to archbuild.1.asciidoc in https://github.com/archlinux/devtools/blob/master/doc/devtools.7.asciidoc

2021-08-04 15:35 UTC, felixonmars commented
The `MANS` list in Makefile should be updated as well, I think.

2021-08-08 15:33 UTC, felixonmars approved these changes

2021-08-19 16:01 UTC, jelly commented on doc/archbuild.1.asciidoc
> +The symlink used to run it will be inspected by archbuild, to determine which target you want it to use.
Maybe this should also explain the configuration file loading when you use `staging-x86_64-build`
```
devtools /usr/share/devtools/pacman-kde-unstable.conf
```

2021-08-19 16:06 UTC, jelly requested changes

2021-08-19 16:06 UTC, jelly commented on doc/archbuild.1.asciidoc
> +'archbuild' is a script to build an Arch Linux package. devtools includes archbuild, but you don't run this command directly.
```suggestion
'archbuild' is a script to build an Arch Linux package. devtools includes archbuild but should only be used via one of the included symlinks:
```

2021-08-19 16:06 UTC, jelly commented on doc/archbuild.1.asciidoc
> +'archbuild' is a script to build an Arch Linux package. devtools includes archbuild, but you don't run this command directly.
I would reword it to not say "you" or that you don't run it directly.

2021-09-08 19:25 UTC, jelly commented
Merged via fd17f53cef61ca5e25219fcc0d555e154cd0af59

2021-09-08 19:25 UTC, closed without merging