doc: Add makechrootpkg man page
archlinux/devtools pull request #66
Opened 2021-08-08 11:30 UTC by yoursweetie

Add makechrootpkg man page.

2021-08-08 11:41 UTC, anthraxx commented
was the close an accident?

2021-08-08 11:47 UTC, yoursweetie commented
> was the close an accident?

Sorry, I found that more than a file is going to be added.

2021-08-08 11:48 UTC, anthraxx commented
please just force push your feature branch instead of re-creating pull requests :cat:

2021-08-08 15:45 UTC, yoursweetie commented
> please just force push your feature branch instead of re-creating pull requests

Sorry to disturb, I added other files which should be added & pushed them to my `add-doc-makechrootpkg` branch. Should I reopen this PR and do something else?

2021-08-15 16:40 UTC, felixonmars approved these changes

2021-08-19 15:53 UTC, jelly requested changes
Apart from some small improvements, it looks good to me!

2021-08-19 15:53 UTC, jelly commented on doc/makechrootpkg.1.asciidoc
> +Run this script in a PKGBUILD dir to build a package inside a
```suggestion
Run this script in a directory containing a PKGBUILD to build a package inside a
```

2021-08-19 15:53 UTC, jelly commented on doc/makechrootpkg.1.asciidoc
> +	Run namcap on the package
```suggestion
	Run namcap on the build package
```

2021-08-19 15:53 UTC, jelly commented on doc/makechrootpkg.1.asciidoc
> +	Run checkpkg on the package
```suggestion
	Run checkpkg on the build package
```

2021-09-07 18:57 UTC, jelly commented
Thanks, merged via 80e8c1fc702e6a0e328bca52d3acf0710c7cc7ff

2021-09-07 18:57 UTC, closed without merging